### ISSUE TITLE
Holding onto prior station

### ISSUE THREAD

**Issue by DavidFB1** [alexis-jaksone/forecast-plus#15]
Recently, I looked at the weather in a different place. Now, it always shows that location. I have to manually change it to my Home station each time, making the icon useless.

The alternate location is not set as a home or favorite. The home location is. I have a few other favorites.

This is in current Firefox with current plugin version. It started doing this a couple of weeks ago.

**Comment by felrya** [comment]
I am having the same issue.

**Comment by alexis-jaksone** [comment]
Is this fixed on the latest release?

**Comment by DavidFB1** [comment]
Yes, thanks!
