### ISSUE TITLE
Weather forecast, map, almanac and details not loaded

### ISSUE THREAD

**Issue by mbacilieri** [alexis-jaksone/forecast-plus#18]
Opening the pop-up will load only the main data.
The forecast, the map, the almanac and all the other details are not loaded: in the "10 days forecast" area there is the "circling" that continue to wait for data, but nothing happens.
Data to be loaded should be https://www.wunderground.com/q/zmw:00000.3.16146?MR=1#forecast-graph that in a "normal" page of the browser works flawlessy.

**Comment by mbacilieri** [comment]
Sorry, it's a duplicate of #12

**Comment by alexis-jaksone** [comment]
Following up this on #12.
