### ISSUE TITLE
Still loading

### ISSUE THREAD

**Issue by tarstudio** [alexis-jaksone/forecast-plus#2]
My Forcast Plus , after one year of perfect use in now not full loading  --  denying me the 10 day forecasts.  Where do I begin??

Thanks,    Peter

**Comment by alexis-jaksone** [comment]
please follow my comment https://github.com/alexis-jaksone/forecast-plus/issues/3 and let me know if it helps

**Comment by tarstudio** [comment]
I believe #4 is my problem and worthy of pursuit.    Thanks for your help.

**Comment by alexis-jaksone** [comment]
#4? This issue can only cause no badge notification not the loading issue. What is your browser?

**Comment by tarstudio** [comment]
Foxfire:  Created:8/30/14    Modified:   2/6/16 Previous version:  1/29/16

**Comment by alexis-jaksone** [comment]
Please re-open if you are still experiencing this issue.
