### ISSUE TITLE
Extension won't load info. 

### ISSUE THREAD

**Issue by Wheezy2** [alexis-jaksone/forecast-plus#51]
Uninstalled a reinstalled. Did not fix. Was working 12 hours ago. I now only get that little sad face. :( 
Weather Underground.com is up and running. TY!!!
[Forecast Plus broken](https://user-images.githubusercontent.com/19244337/69087554-c17c6480-0a14-11ea-9b6a-88a35b52c216.jpg)

**Comment by anichols70** [comment]
Also seeing the same issue. Just get "www.wunderground.com refused to connect".  Have tried uninstalling and reinstalling. No luck.

**Comment by pbajorek** [comment]
Seeing same issue. Says - www.wunderground.com refused to connect. Toolbar continues to update. Running Chrome Version 78.0.3904.108

**Comment by Wheezy2** [comment]
It is still broken. Version 0.3.6 Updated August 21, 2019, in Chrome Version 78.0.3904.108 (Official Build) (64-bit). TY!!

**Comment by Wheezy2** [comment]
TY for the fix!!
