### ISSUE TITLE
Still wont load after your fix.

### ISSUE THREAD

**Issue by Wheezy2** [alexis-jaksone/forecast-plus#52]
It is still broken. Version 0.3.6 Updated August 21, 2019, in Chrome Version 78.0.3904.108 (Official Build) (64-bit). TY!!

**Comment by anichols70** [comment]
Doesn't look like the fix has been pushed to the Chrome store yet.  His fix is 0.3.7 and the store still has 0.3.6.
Any idea when this fix will be pushed?

**Comment by Wheezy2** [comment]
Fixed!! TY!!
