### ISSUE TITLE
Icon shows it is sunny at 10 PM if I am using local reporting station

### ISSUE THREAD

**Issue by Wheezy2** [alexis-jaksone/forecast-plus#58]
The icon shows sunny conditions at 10 PM, etc. when I am on the local reporting station, but the icon changes to correct status when I am on the forecast page of the town I chose. Bizarre.

**Comment by alexis-jaksone** [comment]
Can you share the station URL? To get that open the popup and then press the "Weather" icon to let the page open on a browser tab.

**Comment by Wheezy2** [comment]
https://www.wunderground.com/dashboard/pws/KPAHAVER15?cm_ven=localwx_pwsdash

This is the URL for the station. The icon shows sunny. It is 325 PM. When I go to the forecast page the icon changes to cloudy.The icon should be the same. Right? Thanks. 
     On Thursday, August 19, 2021, 12:23:24 AM EDT, alexis-jaksone ***@***.***> wrote:  
 
 


Can you share the station URL? To get that open the popup and then press the "Weather" icon to let the page open on a browser tab.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by alexis-jaksone** [comment]
Should be fixed by 0.5.3 release.

**Comment by Wheezy2** [comment]
Thank you very much. Be well.
    On Saturday, August 21, 2021, 12:48:26 AM EDT, alexis-jaksone ***@***.***> wrote:  
 
 


Should be fixed by 0.5.3 release.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
