### ISSUE TITLE
chrome://flags/#enable-javascript-harmony

### ISSUE THREAD

**Issue by raddyst** [alexis-jaksone/forecast-plus#6]
If chrome://flags/#enable-javascript-harmony enabled - extension stops working. Tested in Opera beta 36.0.2130.2/ Dev 37.0.2142.0

**Comment by alexis-jaksone** [comment]
It works just fine for me. Do you get an error in the console (chrome://extensions/)?

**Comment by raddyst** [comment]
Really? Test on last stable Opera:
gif - https://imgur.com/6ahI6cN 
video - https://yadi.sk/i/eO0E82iLqnLmg

**Comment by alexis-jaksone** [comment]
It is working just fine on my Mac even when harmony is enabled. Based on your video I can say the extension is not initiating. Please try https://github.com/alexis-jaksone/forecast-plus/blob/master/builds/packed/chrome.zip?raw=true and let me know if it works on harmony enabled Opera or not.

**Comment by raddyst** [comment]
Yes, all ok
