### ISSUE TITLE
Decimal point in Firefox (once again)

### ISSUE THREAD

**Issue by ZX-Commodore-ST** [alexis-jaksone/forecast-plus#66]
I can't reopen issue so I add it once again as it's not fully fixed. https://github.com/alexis-jaksone/forecast-plus/issues/65

**Comment by alexis-jaksone** [comment]
There is nothing I can do. Firefox has a maximum width for the badge text, and when this option is enabled, the number may overflow.

**Comment by ZX-Commodore-ST** [comment]
OK. It's just a minor issue, decimal point is not really needed.
