### ISSUE TITLE
Precip. Accum. Total [in]

### ISSUE THREAD

**Issue by brLouis** [alexis-jaksone/forecast-plus#7]
Hello,
First, I'd like to say that Forecast Plus is a great addon.

But, on the Graph Tab,the Precip. Accum. Total [in] comes up but even though there is Precipitation forecasted for all day on Monday there is no accumulation showing.
I tried changing stations to another one near by and it was the same.
Thank you!

**Comment by alexis-jaksone** [comment]
Hi,

The UI of the panel is from Weather Underground website. Unfortunately there is no control on elements.
