### ISSUE TITLE
10-Day weather forecast will not load

### ISSUE THREAD

**Issue by vgsuvi** [alexis-jaksone/forecast-plus#8]
Every 2 weeks or so ForecastPlus breaks, and will not load the 10-day forecast.  Up until now, I've always been able to fix this by uninstalling the extension and then re-installing.  However, today that does not work anymore.

I am running under Google Chrome, version 49.0.2623.87 (64-bit), under Fedora 17.

**Comment by alexis-jaksone** [comment]
Are you sure it is not compatibility issue with other extensions? Maybe you have an add-on that blocks some resources. Try to load https://www.wunderground.com/ on a browser tab and see if it loads fine or not

**Comment by vgsuvi** [comment]
Hmmm, you are correct.  The wunderground.com web site has the same problem.  It's possibly due to running in an old Linux environment for which Chrome is no longer supported.  Thanks for your help.
