### ISSUE TITLE
Temperature on the badge icon not updating with the site

### ISSUE THREAD

**Issue by ansaksie** [alexis-jaksone/forecast-plus#9]
The temperature that's on the icon next to the address bar sometimes doesn't sync with the site.  I have to click the icon, then switch between BestForecast and NWS in order to get the icon to display the current temperature.  Sometimes it'll update on its own, but eventually it goes back to being stuck until I force it to change.

**Comment by hlynn** [comment]
Just wanted to double up on this reported issue. I'm experiencing identical issue. Have uninstalled and reinstalled to no avail.

**Comment by ogrizo** [comment]
Tripling up. My badge won't update unless I uninstall the extension and re-install. Simply disabling / reenabling doesn't work. 

Also, my drop down screen reports Brutus MIA until I click on one of my recent cities: 
![capture](https://cloud.githubusercontent.com/assets/18168555/14143943/c21ac736-f65b-11e5-998d-aebf76bb732f.JPG)

**Comment by alexis-jaksone** [comment]
@ogrizo follow FAQ 6 to reset the preferece caused the "Page not found" error; http://add0n.com/forecast-plus.html. When the pref is reset you should not have the problem anymore. @ansaksie and @hlynn guys do you have the same issue with the panel? I mean the page not found issue?

**Comment by ansaksie** [comment]
@alexis-jaksone  I don't remember ever seeing the "Page not found" error.  When I click the icon and its drop down page appears, the site loads just fine.  It's just that the temperature on the badge won't update with the site unless I either restart Chrome (I'm not using Firefox) or manually make the temperature change by switching between BestForecast and NWS.  I think it loses the ability the update when my computer goes to sleep for a period of time.

**Comment by ogrizo** [comment]
I'm seeing the FAQ #6: 

> The panel does not show anything. How can I reset the extension back to the default view?
> Forecast plus stores the last visited station and uses that location for your next visit. If for any reason the toolbar panel is blank, you may need to clear this preference. To do so, open a new browser tab and enter "about:config" in the addressbar. now search for extensions.jid1-w3xH9kJhd3KJUp@jetpack.current-url and right click on it and press reset. Forecast Plus should load the default location now.

I'm running Chrome Version 49.0.2623.110 m. Where do I find this setting to change in Chrome? I think the about:config is a Firefox thing. I've tried chrome:flags but not finding a Forecast specific entry to modify. Thanks...

**Comment by alexis-jaksone** [comment]
Chrome users please try this version, https://github.com/alexis-jaksone/forecast-plus/blob/master/builds/packed/chrome.zip?raw=true

Download the ZIP package and extract it in a folder. Now open chrome://extensions/ in a tab and check "Developer mode". Point "Load Unpacked Extension" to the root of the extracted folder and let me know if it fixes" the badge is not getting updates" problem.

**Comment by alexis-jaksone** [comment]
@ogrizo in Chrome you can simply trash the extension and re-install it to clear all the preferences. There is no need to delete an individual pref.

**Comment by ogrizo** [comment]
Okay, yes, trashing and reinstalling extension worked. Sorry, thought I'd tried that but apparently not; my bad. Anywho, all's well now and it appears to be working properly using original extension from chrome extension site (not zip you posted above which I've not tried). Thanks!
